apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fiscal-tarsier-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-hub/fiscal-tarsier-java-springboot-gitops